version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  app:
    container_name: app
    depends_on:
      - mysql
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 9090:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/volume/mysql:/var/lib/mysql

