version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
  app:
    container_name: app
    depends_on:
      - db
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www
  pgadmin:
    image: dpage/pgadmin4:7.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
  db:
    container_name: db
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./src/.env
    volumes:
      - ./db:/var/lib/postgresql/data

